<?php
define('PERMISSIONS',
[
    'view_dashbord',
    'add_categories',
    'delete_categories',
    'edit_categories',
    'view_categories',
    'view_roles',
    'edit_roles',
    'add_roles',
    'delete_roles',
     'view_user',
    'add_user',
    'edit_user',
    'view_order',
    'delete_order',
    'view_ads',

]);
